version: "3.9"
services:
  db:
    image: mysql:8.0.35-debian
    container_name: products-backend-db
    ports: 
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=products
    volumes:
      - ./config/prod/mysql_dump:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql #Opcional
  app:
    build: .
    container_name: products-backend-api
    volumes:
      - ./app:/var/www/html/app
      - ./config/prod/virtualhosts/productsmmira.api.chickenkiller.com:/etc/nginx/sites-enabled/productsmmira.api.chickenkiller.com
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - db
volumes:
  mysql-data: #Opcional (si queremos mantener los datos de la base de datos)